# Generated by Django 4.1.3 on 2022-11-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
