# Generated by Django 4.1.3 on 2022-11-22 13:39

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_bio_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, upload_to=apps.user.models.user_image_rename),
        ),
    ]
