# Generated by Django 4.1.3 on 2022-11-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_student_teacher_alter_user_role'),
        ('course', '0003_alter_group_start_time_studentgroup_querycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('payment_type', models.CharField(choices=[('click', 'click'), ('naqd', 'naqd'), ('plastik', 'plastik')], max_length=8)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
